### ISSUE TITLE
ocsysinfo.exe exits after launching on windows 10.

### ISSUE THREAD

**Issue by Vishal-09-00** [KernelWanderers/OCSysInfo#28]

**Comment by kernel-dev** [comment]
Could you provide more information? This isn't sufficient to actually pin-point the issue.

**Comment by kernel-dev** [comment]
Tested on my machine. Seems to be working fine. I cannot notice any errors in the log that would prevent the application from starting. 
![image](https://user-images.githubusercontent.com/61620747/209222407-01d0b706-b785-41f7-bee6-d8d7a5a15258.png)

**Comment by Vishal-09-00** [comment]
> Tested on my machine. Seems to be working fine. I cannot notice any errors in the log that would prevent the application from starting. ![image](https://user-images.githubusercontent.com/61620747/209222407-01d0b706-b785-41f7-bee6-d8d7a5a15258.png)



> Could you provide more information? This isn't sufficient to actually pin-point the issue.

The executable just straightaway crashes without any errors.

https://user-images.githubusercontent.com/75847766/209259311-7630014e-eac5-404b-9d62-97a519300b3f.mp4

Specs:
![image](https://user-images.githubusercontent.com/75847766/209259430-04423b6e-6275-464a-a8dc-74029c862689.png)

**Comment by Vishal-09-00** [comment]
> > Tested on my machine. Seems to be working fine. I cannot notice any errors in the log that would prevent the application from starting. ![image](https://user-images.githubusercontent.com/61620747/209222407-01d0b706-b785-41f7-bee6-d8d7a5a15258.png)
> 
> > Could you provide more information? This isn't sufficient to actually pin-point the issue.
> 
> The executable just straightaway crashes without any errors.
> 
>  Test.1.mp4 
> Specs: ![image](https://user-images.githubusercontent.com/75847766/209259430-04423b6e-6275-464a-a8dc-74029c862689.png)

Screen capture of the above video at 00:45 secs shows this error before closing.
![image](https://user-images.githubusercontent.com/75847766/209259769-89e50827-3482-4df5-b8c5-7066ecc02f4f.png)

**Comment by Vishal-09-00** [comment]
Screen capture of the above video at 00:45 secs shows this error before closing.
![image](https://user-images.githubusercontent.com/75847766/209260194-f255c65a-02e9-436d-96b8-9cbdbfe7e509.png)

**Comment by Mahas1** [comment]
Looks like the program is trying to connect to raw.githubusercontent.com and the request times out.
 
Try turning off your internet and opening the executable or opening it with the `--offline` argument

**Comment by Vishal-09-00** [comment]
Using --offline generated this ![IMG-20221223-WA0000.jpg](https://user-images.githubusercontent.com/75847766/209271925-e034688d-a5d9-46ac-8792-74aacb6a03f0.jpg)

And without internet it's just getting closed.

**Comment by kernel-dev** [comment]
I'm unable to reproduce on my machine, on either branch. Though, I believe I can see why this fails. It is a bit of an oversight on our behalf, as we simply fetched the `version.json` file from the main branch (in our releases-source branch) to not have to update both branches for the version.

I think it's a flawed idea in general to fetch from the main branch for all consecutive versions, since the versioning will not be valid. I've refactored this to use local files in order to obtain the versioning in 2885309 (releases-source) and a7dbcfb (main) respectively.

Theoretically, it should work now. Do report back on whether or not it works. Thanks for bringing this to our attention.

**Comment by Vishal-09-00** [comment]
So, now I am able to run the script using "python3 main.py" through terminal. But the problem still persist for the executable file. Upon opening it just crashes. 

![vlcsnap-2022-12-23-19h46m45s690](https://user-images.githubusercontent.com/75847766/209351670-51a951a6-44fb-4905-9fb6-a8e7a73320e6.png)

**Comment by kernel-dev** [comment]
Try with the latest releases. I've updated it, once again, because of an issue in the code. Should work OK now. 
![image](https://user-images.githubusercontent.com/61620747/209413619-3787f696-9ce4-4458-adc6-d51a35b2bcf8.png)

**Comment by Vishal-09-00** [comment]
Great !! 
Now the issue has been resolved.
